/*

OpenGL ES 1.0 compatibility layer for Samsung Omnia 2
Copyright (c) 2009 Ivan Podogov http://omnia2gl.sourceforge.net

This software is provided 'as-is', without any express or implied warranty.
In no event will the authors be held liable for any damages arising from the use of this software.
Permission is granted to anyone to use this software for any purpose, 
including commercial applications, and to alter it and redistribute it freely, 
subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required.
2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.
3. This notice may not be removed or altered from any source distribution.

*/

#include "stdafx.h"

#define GL_OES_draw_texture
#define GL_OES_matrix_palette

#pragma comment(linker, "/export:glActiveTexture=myglActiveTexture")
#pragma comment(linker, "/export:glAlphaFunc=myglAlphaFunc")
#pragma comment(linker, "/export:glAlphaFuncx=myglAlphaFuncx")
#pragma comment(linker, "/export:glBindBuffer=myglBindBuffer")
#pragma comment(linker, "/export:glBindTexture=myglBindTexture")
#pragma comment(linker, "/export:glBlendFunc=myglBlendFunc")
#pragma comment(linker, "/export:glBufferData=myglBufferData")
#pragma comment(linker, "/export:glBufferSubData=myglBufferSubData")
#pragma comment(linker, "/export:glClear=myglClear")
#pragma comment(linker, "/export:glClearColor=myglClearColor")
#pragma comment(linker, "/export:glClearColorx=myglClearColorx")
#pragma comment(linker, "/export:glClearDepthf=myglClearDepthf")
#pragma comment(linker, "/export:glClearDepthx=myglClearDepthx")
#pragma comment(linker, "/export:glClearStencil=myglClearStencil")
#pragma comment(linker, "/export:glClientActiveTexture=myglClientActiveTexture")
#pragma comment(linker, "/export:glClipPlanex=myglClipPlanex")
#pragma comment(linker, "/export:glClipPlanef=myglClipPlanef")
#pragma comment(linker, "/export:glColor4f=myglColor4f")
#pragma comment(linker, "/export:glColor4ub=myglColor4ub")
#pragma comment(linker, "/export:glColor4x=myglColor4x")
#pragma comment(linker, "/export:glColorMask=myglColorMask")
#pragma comment(linker, "/export:glColorPointer=myglColorPointer")
#pragma comment(linker, "/export:glCompressedTexImage2D=myglCompressedTexImage2D")
#pragma comment(linker, "/export:glCompressedTexSubImage2D=myglCompressedTexSubImage2D")
#pragma comment(linker, "/export:glCopyTexImage2D=myglCopyTexImage2D")
#pragma comment(linker, "/export:glCopyTexSubImage2D=myglCopyTexSubImage2D")
#pragma comment(linker, "/export:glCullFace=myglCullFace")
#pragma comment(linker, "/export:glDeleteBuffers=myglDeleteBuffers")
#pragma comment(linker, "/export:glDeleteTextures=myglDeleteTextures")
#pragma comment(linker, "/export:glDepthFunc=myglDepthFunc")
#pragma comment(linker, "/export:glDepthMask=myglDepthMask")
#pragma comment(linker, "/export:glDepthRangef=myglDepthRangef")
#pragma comment(linker, "/export:glDepthRangex=myglDepthRangex")
#pragma comment(linker, "/export:glDisable=myglDisable")
#pragma comment(linker, "/export:glDisableClientState=myglDisableClientState")
#pragma comment(linker, "/export:glDrawArrays=myglDrawArrays")
#pragma comment(linker, "/export:glDrawElements=myglDrawElements")
#pragma comment(linker, "/export:glEnable=myglEnable")
#pragma comment(linker, "/export:glEnableClientState=myglEnableClientState")
#pragma comment(linker, "/export:glFinish=myglFinish")
#pragma comment(linker, "/export:glFlush=myglFlush")
#pragma comment(linker, "/export:glFogf=myglFogf")
#pragma comment(linker, "/export:glFogfv=myglFogfv")
#pragma comment(linker, "/export:glFogx=myglFogx")
#pragma comment(linker, "/export:glFogxv=myglFogxv")
#pragma comment(linker, "/export:glFrontFace=myglFrontFace")
#pragma comment(linker, "/export:glFrustumf=myglFrustumf")
#pragma comment(linker, "/export:glFrustumx=myglFrustumx")
#pragma comment(linker, "/export:glGetBooleanv=myglGetBooleanv")
#pragma comment(linker, "/export:glGetBufferParameteriv=myglGetBufferParameteriv")
#pragma comment(linker, "/export:glGetClipPlanef=myglGetClipPlanef")
#pragma comment(linker, "/export:glGetClipPlanex=myglGetClipPlanex")
#pragma comment(linker, "/export:glGenBuffers=myglGenBuffers")
#pragma comment(linker, "/export:glGenTextures=myglGenTextures")
#pragma comment(linker, "/export:glGetError=myglGetError")
#pragma comment(linker, "/export:glGetFixedv=myglGetFixedv")
#pragma comment(linker, "/export:glGetFloatv=myglGetFloatv")
#pragma comment(linker, "/export:glGetIntegerv=myglGetIntegerv")
#pragma comment(linker, "/export:glGetLightfv=myglGetLightfv")
#pragma comment(linker, "/export:glGetLightxv=myglGetLightxv")
#pragma comment(linker, "/export:glGetMaterialfv=myglGetMaterialfv")
#pragma comment(linker, "/export:glGetMaterialxv=myglGetMaterialxv")
#pragma comment(linker, "/export:glGetPointerv=myglGetPointerv")
#pragma comment(linker, "/export:glGetString=myglGetString")
#pragma comment(linker, "/export:glGetTexEnviv=myglGetTexEnviv")
#pragma comment(linker, "/export:glGetTexEnvfv=myglGetTexEnvfv")
#pragma comment(linker, "/export:glGetTexEnvxv=myglGetTexEnvxv")
#pragma comment(linker, "/export:glGetTexParameteriv=myglGetTexParameteriv")
#pragma comment(linker, "/export:glGetTexParameterfv=myglGetTexParameterfv")
#pragma comment(linker, "/export:glGetTexParameterxv=myglGetTexParameterxv")
#pragma comment(linker, "/export:glHint=myglHint")
#pragma comment(linker, "/export:glIsBuffer=myglIsBuffer")
#pragma comment(linker, "/export:glIsEnabled=myglIsEnabled")
#pragma comment(linker, "/export:glIsTexture=myglIsTexture")
#pragma comment(linker, "/export:glLightModelf=myglLightModelf")
#pragma comment(linker, "/export:glLightModelfv=myglLightModelfv")
#pragma comment(linker, "/export:glLightModelx=myglLightModelx")
#pragma comment(linker, "/export:glLightModelxv=myglLightModelxv")
#pragma comment(linker, "/export:glLightf=myglLightf")
#pragma comment(linker, "/export:glLightfv=myglLightfv")
#pragma comment(linker, "/export:glLightx=myglLightx")
#pragma comment(linker, "/export:glLightxv=myglLightxv")
#pragma comment(linker, "/export:glLineWidth=myglLineWidth")
#pragma comment(linker, "/export:glLineWidthx=myglLineWidthx")
#pragma comment(linker, "/export:glLoadIdentity=myglLoadIdentity")
#pragma comment(linker, "/export:glLoadMatrixf=myglLoadMatrixf")
#pragma comment(linker, "/export:glLoadMatrixx=myglLoadMatrixx")
#pragma comment(linker, "/export:glLogicOp=myglLogicOp")
#pragma comment(linker, "/export:glMaterialf=myglMaterialf")
#pragma comment(linker, "/export:glMaterialfv=myglMaterialfv")
#pragma comment(linker, "/export:glMaterialx=myglMaterialx")
#pragma comment(linker, "/export:glMaterialxv=myglMaterialxv")
#pragma comment(linker, "/export:glMatrixMode=myglMatrixMode")
#pragma comment(linker, "/export:glMultMatrixf=myglMultMatrixf")
#pragma comment(linker, "/export:glMultMatrixx=myglMultMatrixx")
#pragma comment(linker, "/export:glMultiTexCoord4f=myglMultiTexCoord4f")
#pragma comment(linker, "/export:glMultiTexCoord4x=myglMultiTexCoord4x")
#pragma comment(linker, "/export:glNormal3f=myglNormal3f")
#pragma comment(linker, "/export:glNormal3x=myglNormal3x")
#pragma comment(linker, "/export:glNormalPointer=myglNormalPointer")
#pragma comment(linker, "/export:glOrthof=myglOrthof")
#pragma comment(linker, "/export:glOrthox=myglOrthox")
#pragma comment(linker, "/export:glPixelStorei=myglPixelStorei")
#pragma comment(linker, "/export:glPointParameterf=myglPointParameterf")
#pragma comment(linker, "/export:glPointParameterfv=myglPointParameterfv")
#pragma comment(linker, "/export:glPointParameterx=myglPointParameterx")
#pragma comment(linker, "/export:glPointParameterxv=myglPointParameterxv")
#pragma comment(linker, "/export:glPointSize=myglPointSize")
#pragma comment(linker, "/export:glPointSizex=myglPointSizex")
#pragma comment(linker, "/export:glPolygonOffset=myglPolygonOffset")
#pragma comment(linker, "/export:glPolygonOffsetx=myglPolygonOffsetx")
#pragma comment(linker, "/export:glPopMatrix=myglPopMatrix")
#pragma comment(linker, "/export:glPushMatrix=myglPushMatrix")
#pragma comment(linker, "/export:glReadPixels=myglReadPixels")
#pragma comment(linker, "/export:glRotatef=myglRotatef")
#pragma comment(linker, "/export:glRotatex=myglRotatex")
#pragma comment(linker, "/export:glSampleCoverage=myglSampleCoverage")
#pragma comment(linker, "/export:glSampleCoveragex=myglSampleCoveragex")
#pragma comment(linker, "/export:glScalef=myglScalef")
#pragma comment(linker, "/export:glScalex=myglScalex")
#pragma comment(linker, "/export:glScissor=myglScissor")
#pragma comment(linker, "/export:glShadeModel=myglShadeModel")
#pragma comment(linker, "/export:glStencilFunc=myglStencilFunc")
#pragma comment(linker, "/export:glStencilMask=myglStencilMask")
#pragma comment(linker, "/export:glStencilOp=myglStencilOp")
#pragma comment(linker, "/export:glTexCoordPointer=myglTexCoordPointer")
#pragma comment(linker, "/export:glTexEnvf=myglTexEnvf")
#pragma comment(linker, "/export:glTexEnvfv=myglTexEnvfv")
#pragma comment(linker, "/export:glTexEnvi=myglTexEnvi")
#pragma comment(linker, "/export:glTexEnviv=myglTexEnviv")
#pragma comment(linker, "/export:glTexEnvx=myglTexEnvx")
#pragma comment(linker, "/export:glTexEnvxv=myglTexEnvxv")
#pragma comment(linker, "/export:glTexImage2D=myglTexImage2D")
#pragma comment(linker, "/export:glTexParameteri=myglTexParameteri")
#pragma comment(linker, "/export:glTexParameteriv=myglTexParameteriv")
#pragma comment(linker, "/export:glTexParameterf=myglTexParameterf")
#pragma comment(linker, "/export:glTexParameterfv=myglTexParameterfv")
#pragma comment(linker, "/export:glTexParameterx=myglTexParameterx")
#pragma comment(linker, "/export:glTexParameterxv=myglTexParameterxv")
#pragma comment(linker, "/export:glTexSubImage2D=myglTexSubImage2D")
#pragma comment(linker, "/export:glTranslatef=myglTranslatef")
#pragma comment(linker, "/export:glTranslatex=myglTranslatex")
#pragma comment(linker, "/export:glVertexPointer=myglVertexPointer")
#pragma comment(linker, "/export:glViewport=myglViewport")

#ifdef GL_OES_matrix_palette
#pragma comment(linker, "/export:glCurrentPaletteMatrixOES=myglCurrentPaletteMatrixOES")
#pragma comment(linker, "/export:glLoadPaletteFromModelViewMatrixOES=myglLoadPaletteFromModelViewMatrixOES")
#pragma comment(linker, "/export:glMatrixIndexPointerOES=myglMatrixIndexPointerOES")
#pragma comment(linker, "/export:glWeightPointerOES=myglWeightPointerOES")
#endif

#pragma comment(linker, "/export:glPointSizePointerOES=myglPointSizePointerOES")

#ifdef GL_OES_draw_texture
#pragma comment(linker, "/export:glDrawTexsOES=myglDrawTexsOES")
#pragma comment(linker, "/export:glDrawTexiOES=myglDrawTexiOES")
#pragma comment(linker, "/export:glDrawTexfOES=myglDrawTexfOES")
#pragma comment(linker, "/export:glDrawTexxOES=myglDrawTexxOES")
#pragma comment(linker, "/export:glDrawTexsvOES=myglDrawTexsvOES")
#pragma comment(linker, "/export:glDrawTexivOES=myglDrawTexivOES")
#pragma comment(linker, "/export:glDrawTexfvOES=myglDrawTexfvOES")
#pragma comment(linker, "/export:glDrawTexxvOES=myglDrawTexxvOES")
#endif

#pragma comment(linker, "/export:eglGetError=myeglGetError")
#pragma comment(linker, "/export:eglGetDisplay=myeglGetDisplay")
#pragma comment(linker, "/export:eglInitialize=myeglInitialize")
#pragma comment(linker, "/export:eglTerminate=myeglTerminate")
#pragma comment(linker, "/export:eglQueryString=myeglQueryString")
#pragma comment(linker, "/export:eglGetProcAddress=myeglGetProcAddress")
#pragma comment(linker, "/export:eglGetConfigs=myeglGetConfigs")
#pragma comment(linker, "/export:eglChooseConfig=myeglChooseConfig")
#pragma comment(linker, "/export:eglGetConfigAttrib=myeglGetConfigAttrib")
#pragma comment(linker, "/export:eglCreateWindowSurface=myeglCreateWindowSurface")
#pragma comment(linker, "/export:eglCreatePixmapSurface=myeglCreatePixmapSurface")
#pragma comment(linker, "/export:eglCreatePbufferSurface=myeglCreatePbufferSurface")
#pragma comment(linker, "/export:eglDestroySurface=myeglDestroySurface")
#pragma comment(linker, "/export:eglQuerySurface=myeglQuerySurface")
#pragma comment(linker, "/export:eglSurfaceAttrib=myeglSurfaceAttrib")
#pragma comment(linker, "/export:eglBindTexImage=myeglBindTexImage")
#pragma comment(linker, "/export:eglReleaseTexImage=myeglReleaseTexImage")
#pragma comment(linker, "/export:eglSwapInterval=myeglSwapInterval")
#pragma comment(linker, "/export:eglCreateContext=myeglCreateContext")
#pragma comment(linker, "/export:eglDestroyContext=myeglDestroyContext")
#pragma comment(linker, "/export:eglMakeCurrent=myeglMakeCurrent")
#pragma comment(linker, "/export:eglGetCurrentContext=myeglGetCurrentContext")
#pragma comment(linker, "/export:eglGetCurrentSurface=myeglGetCurrentSurface")
#pragma comment(linker, "/export:eglGetCurrentDisplay=myeglGetCurrentDisplay")
#pragma comment(linker, "/export:eglQueryContext=myeglQueryContext")
#pragma comment(linker, "/export:eglWaitGL=myeglWaitGL")
#pragma comment(linker, "/export:eglWaitNative=myeglWaitNative")
#pragma comment(linker, "/export:eglSwapBuffers=myeglSwapBuffers")
#pragma comment(linker, "/export:eglCopyBuffers=myeglCopyBuffers")
//#pragma comment(linker, "/export:glQueryMatrixxOES=myglQueryMatrixxOES")
#pragma comment(linker, "/export:eglGetColorBufferQUALCOMM=myeglGetColorBufferQUALCOMM")

#pragma comment(lib,"libGLESv2.lib")
#pragma comment(lib,"libEGL.lib")

/*
#pragma comment(linker, "/export:eglBindAPI=myeglBindAPI")
#pragma comment(linker, "/export:eglCreatePbufferFromClientBuffer=myeglCreatePbufferFromClientBuffer")
#pragma comment(linker, "/export:eglQueryAPI=myeglQueryAPI")
#pragma comment(linker, "/export:eglReleaseThread=myeglReleaseThread")
#pragma comment(linker, "/export:eglWaitClient=myeglWaitClient")
#pragma comment(linker, "/export:glAttachShader=myglAttachShader")
#pragma comment(linker, "/export:glBindAttribLocation=myglBindAttribLocation")
#pragma comment(linker, "/export:glBindFramebuffer=myglBindFramebuffer")
#pragma comment(linker, "/export:glBindRenderbuffer=myglBindRenderbuffer")
#pragma comment(linker, "/export:glBlendColor=myglBlendColor")
#pragma comment(linker, "/export:glBlendEquation=myglBlendEquation")
#pragma comment(linker, "/export:glBlendEquationSeparate=myglBlendEquationSeparate")
#pragma comment(linker, "/export:glBlendFuncSeparate=myglBlendFuncSeparate")
#pragma comment(linker, "/export:glCheckFramebufferStatus=myglCheckFramebufferStatus")
#pragma comment(linker, "/export:glCompileShader=myglCompileShader")
#pragma comment(linker, "/export:glCreateProgram=myglCreateProgram")
#pragma comment(linker, "/export:glCreateShader=myglCreateShader")
#pragma comment(linker, "/export:glDeleteFramebuffers=myglDeleteFramebuffers")
#pragma comment(linker, "/export:glDeleteProgram=myglDeleteProgram")
#pragma comment(linker, "/export:glDeleteShader=myglDeleteShader")
#pragma comment(linker, "/export:glDetachShader=myglDetachShader")
#pragma comment(linker, "/export:glDisableVertexAttribArray=myglDisableVertexAttribArray")
#pragma comment(linker, "/export:glEnableVertexAttribArray=myglEnableVertexAttribArray")
#pragma comment(linker, "/export:glFramebufferRenderbuffer=myglFramebufferRenderbuffer")
#pragma comment(linker, "/export:glFramebufferTexture2D=myglFramebufferTexture2D")
#pragma comment(linker, "/export:glGenerateMipmap=myglGenerateMipmap")
#pragma comment(linker, "/export:glGenFramebuffers=myglGenFramebuffers")
#pragma comment(linker, "/export:glGenRenderbuffers=myglGenRenderbuffers")
#pragma comment(linker, "/export:glGetActiveAttrib=myglGetActiveAttrib")
#pragma comment(linker, "/export:glGetActiveUniform=myglGetActiveUniform")
#pragma comment(linker, "/export:glGetAttachedShaders=myglGetAttachedShaders")
#pragma comment(linker, "/export:glGetAttribLocation=myglGetAttribLocation")
#pragma comment(linker, "/export:glGetFramebufferAttachmentParameteriv=myglGetFramebufferAttachmentParameteriv")
#pragma comment(linker, "/export:glGetProgramInfoLog=myglGetProgramInfoLog")
#pragma comment(linker, "/export:glGetProgramiv=myglGetProgramiv")
#pragma comment(linker, "/export:glGetRenderbufferParameteriv=myglGetRenderbufferParameteriv")
#pragma comment(linker, "/export:glGetShaderInfoLog=myglGetShaderInfoLog")
#pragma comment(linker, "/export:glGetShaderiv=myglGetShaderiv")
#pragma comment(linker, "/export:glGetShaderPrecisionFormat=myglGetShaderPrecisionFormat")
#pragma comment(linker, "/export:glGetShaderSource=myglGetShaderSource")
#pragma comment(linker, "/export:glGetUniformfv=myglGetUniformfv")
#pragma comment(linker, "/export:glGetUniformiv=myglGetUniformiv")
#pragma comment(linker, "/export:glGetUniformLocation=myglGetUniformLocation")
#pragma comment(linker, "/export:glGetVertexAttribfv=myglGetVertexAttribfv")
#pragma comment(linker, "/export:glGetVertexAttribiv=myglGetVertexAttribiv")
#pragma comment(linker, "/export:glGetVertexAttribPointerv=myglGetVertexAttribPointerv")
#pragma comment(linker, "/export:glIsFramebuffer=myglIsFramebuffer")
#pragma comment(linker, "/export:glIsProgram=myglIsProgram")
#pragma comment(linker, "/export:glIsRenderbuffer=myglIsRenderbuffer")
#pragma comment(linker, "/export:glIsShader=myglIsShader")
#pragma comment(linker, "/export:glLinkProgram=myglLinkProgram")
#pragma comment(linker, "/export:glReleaseShaderCompiler=myglReleaseShaderCompiler")
#pragma comment(linker, "/export:glRenderbufferStorage=myglRenderbufferStorage")
#pragma comment(linker, "/export:glShaderBinary=myglShaderBinary")
#pragma comment(linker, "/export:glShaderSource=myglShaderSource")
#pragma comment(linker, "/export:glStencilFuncSeparate=myglStencilFuncSeparate")
#pragma comment(linker, "/export:glStencilOpSeparate=myglStencilOpSeparate")
#pragma comment(linker, "/export:glUniform1i=myglUniform1i")
#pragma comment(linker, "/export:glUniform2i=myglUniform2i")
#pragma comment(linker, "/export:glUniform3i=myglUniform3i")
#pragma comment(linker, "/export:glUniform4i=myglUniform4i")
#pragma comment(linker, "/export:glUniform1f=myglUniform1f")
#pragma comment(linker, "/export:glUniform2f=myglUniform2f")
#pragma comment(linker, "/export:glUniform3f=myglUniform3f")
#pragma comment(linker, "/export:glUniform4f=myglUniform4f")
#pragma comment(linker, "/export:glUniform1iv=myglUniform1iv")
#pragma comment(linker, "/export:glUniform2iv=myglUniform2iv")
#pragma comment(linker, "/export:glUniform3iv=myglUniform3iv")
#pragma comment(linker, "/export:glUniform4iv=myglUniform4iv")
#pragma comment(linker, "/export:glUniform1fv=myglUniform1fv")
#pragma comment(linker, "/export:glUniform2fv=myglUniform2fv")
#pragma comment(linker, "/export:glUniform3fv=myglUniform3fv")
#pragma comment(linker, "/export:glUniform4fv=myglUniform4fv")
#pragma comment(linker, "/export:glUniformMatrix2fv=myglUniformMatrix2fv")
#pragma comment(linker, "/export:glUniformMatrix3fv=myglUniformMatrix3fv")
#pragma comment(linker, "/export:glUniformMatrix4fv=myglUniformMatrix4fv")
#pragma comment(linker, "/export:glUseProgram=myglUseProgram")
#pragma comment(linker, "/export:glValidateProgram=myglValidateProgram")
#pragma comment(linker, "/export:glVertexAttrib1f=myglVertexAttrib1f")
#pragma comment(linker, "/export:glVertexAttrib2f=myglVertexAttrib2f")
#pragma comment(linker, "/export:glVertexAttrib3f=myglVertexAttrib3f")
#pragma comment(linker, "/export:glVertexAttrib4f=myglVertexAttrib4f")
#pragma comment(linker, "/export:glVertexAttrib1fv=myglVertexAttrib1fv")
#pragma comment(linker, "/export:glVertexAttrib2fv=myglVertexAttrib2fv")
#pragma comment(linker, "/export:glVertexAttrib3fv=myglVertexAttrib3fv")
#pragma comment(linker, "/export:glVertexAttrib4fv=myglVertexAttrib4fv")
#pragma comment(linker, "/export:glVertexAttribPointer=myglVertexAttribPointer")
*/

