#ifndef _SampleVert_h_
#define _SampleVert_h_


// Header generated from binary by WriteAsBinHeader()..
static const int SampleVertLength = 101;
static const unsigned int SampleVert[SampleVertLength]={
	0x20205356,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000006,	0x00000006,	0x00000000,	0x00000000,	0x00000002,	0x00000002,
	0x00000001,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000028,	0x00000000,	0x00000000,	0x02020000,
	0x237820E4,	0x00000000,	0x00E40100,	0x02035500,	0x2EF820E4,	0x00000000,	0x00E40100,	0x0204AA00,	0x2EF820E4,	0x00000000,
	0x00E40100,	0x0205FF00,	0x0EF800E4,	0x00000000,	0x00000000,	0x00010000,	0x00F801E4,	0x00000000,	0x00000000,	0x00000000,
	0x1E000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x3F800000,	0x3F800000,	0x3F800000,	0x3F800000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x0000000C,	0x00000009,	0x00000009,	0x00000000,
	0x00000000,	0x00000016,	0x00000008,	0x00000009,	0x00000000,	0x00000004,	0x00000000,	0x0000000B,	0x00000009,	0x00010004,
	0x00000000,	0x00000023,	0x00000004,	0x00000009,	0x00010004,	0x00000004,	0x0000001F,	0x00000003,	0x0000000E,	0x00020001,
	0x00000008,	0x505F6C67,	0x7469736F,	0x006E6F69,	0x74726576,	0x6F507865,	0x65740073,	0x6F6F4378,	0x6D006472,	0x74007076,
	0x00437865,};

//checksum generated by simpleCheckSum()
static const unsigned int SampleVertCheckSum = 127;

static const char* SampleVertText = 
	"#ifdef GL_ES\n"
	"precision highp float;\n"
	"#endif\n"
	"\n"
	"attribute vec4 vertexPos;\n"
	"attribute vec4 texCoord;\n"
	"\n"
	"uniform mat4 mvp;\n"
	"\n"
	"varying vec4 texC;\n"
	"\n"
	"void main()\n"
	"{\n"
	"    gl_Position = mvp * vertexPos;\n"
	"\n"
	"    texC = texCoord;\n"
	"\n"
	"}\n"
	"\n"
	"";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader SampleVertShader(SampleVertText, SampleVert, SampleVertLength, SampleVertCheckSum);


#endif


#endif //_SampleVert_h_
