#ifndef _SampleFrag_h_
#define _SampleFrag_h_


// Header generated from binary by WriteAsBinHeader()..
static const int SampleFragLength = 56;
static const unsigned int SampleFrag[SampleFragLength]={
	0x20205350,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000002,	0x00000004,	0x00000000,	0x00000000,	0x00000001,	0x00000000,
	0x00000000,	0x00000001,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000010,	0x00000000,	0x00000000,	0x0000E407,
	0x107A10E4,	0x00000000,	0x00000000,	0x00000000,	0x1E000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x3F800000,	0x3F800000,	0x3F800000,	0x3F800000,	0x3F800000,	0x00000000,	0x00000000,	0x00000000,	0x3F800000,	0x00000000,
	0x00000000,	0x00000000,	0x0000000B,	0x00000004,	0x00000009,	0x00000000,	0x00000000,	0x00000000,	0x0000000A,	0x0000000F,
	0x00030005,	0x00000000,	0x49786554,	0x6567616D,	0x74003073,	0x00437865,};

//checksum generated by simpleCheckSum()
static const unsigned int SampleFragCheckSum = 87;

static const char* SampleFragText = 
	"\n"
	"#-------------------------------------------------\n"
	"# ORION - OpenGL ES 2.0 Shading Language Compiler\n"
	"# SAMSUNG INDIA SOFTWARE OPERATIONS PVT. LTD.\n"
	"# Compiler Version    : v04.00.03\n"
	"# Release Date        : 30.06.2008\n"
	"# FIMG VERSION      : FIMGv1.5\n"
	"# Optimizer Options :  -O\n"
	"#-------------------------------------------------\n"
	"\n"
	"ps_3_0\n"
	"\n"
	"fimg_version    0x01020000\n"
	"\n"
	"dcl_s2_TexImages0    s0\n"
	"dcl_f4_texC    v0.x\n"
	"\n"
	"def c2, 1.000000, 0, 0, 0\n"
	"def c1, 1.0, 1.0, 1.0, 1.0\n"
	"def c0, 0.0, 0.0, 0.0, 0.0\n"
	"def c3, 1.0, 0.0, 0.0, 0.0\n"
	"\n"
	"label start\n"
	"label main_\n"
	"texld_sat oColor.xyzw, v0.xyzw, s0    # TexImages0=s0\n"
	"label main_end\n"
	"ret\n"
	"# 3 instructions, 5 C regs, 1 R regs \n"
	"";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader SampleFragShader(SampleFragText, SampleFrag, SampleFragLength, SampleFragCheckSum);


#endif


#endif //_SampleFrag_h_
