#ifndef _ColorVert_h_
#define _ColorVert_h_


// Header generated from binary by WriteAsBinHeader()..
static const int ColorVertLength = 107;
static const unsigned int ColorVert[ColorVertLength]={
	0x20205356,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000006,	0x00000006,	0x00000000,	0x00000000,	0x00000002,	0x00000002,
	0x00000001,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x0000003E,	0x00000000,	0x00000000,	0x02020000,
	0x237820E4,	0x00000000,	0x00E40100,	0x02035500,	0x2EF820E4,	0x00000000,	0x00E40100,	0x0204AA00,	0x2EF820E4,	0x00000000,
	0x00E40100,	0x0205FF00,	0x0EF800E4,	0x00000000,	0x00000000,	0x00010000,	0x00F801E4,	0x00000000,	0x00000000,	0x00000000,
	0x1E000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x3F800000,	0x3F800000,	0x3F800000,	0x3F800000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x0000000C,	0x00000006,	0x00000009,	0x00000000,
	0x00000000,	0x00000013,	0x00000005,	0x00000009,	0x00000000,	0x00000004,	0x00000000,	0x0000000B,	0x00000009,	0x00010004,
	0x00000000,	0x00000033,	0x0000000A,	0x00000009,	0x00010004,	0x00000004,	0x00000019,	0x00000019,	0x0000000E,	0x00020001,
	0x00000008,	0x505F6C67,	0x7469736F,	0x006E6F69,	0x74726556,	0x43007865,	0x726F6C6F,	0x646F4D00,	0x69566C65,	0x72507765,
	0x63656A6F,	0x6E6F6974,	0x7274614D,	0x46007869,	0x746E6F72,	0x6F6C6F43,	0x00000072,};

//checksum generated by simpleCheckSum()
static const unsigned int ColorVertCheckSum = 88;

static const char* ColorVertText = 
	"#ifdef GL_ES\n"
	"precision highp float;\n"
	"#endif\n"
	"\n"
	"attribute vec4 Vertex;\n"
	"attribute vec4 Color;\n"
	"\n"
	"uniform mat4 ModelViewProjectionMatrix;\n"
	"\n"
	"varying vec4 FrontColor;\n"
	"\n"
	"void main()\n"
	"{\n"
	"    gl_Position = ModelViewProjectionMatrix * Vertex;\n"
	"    FrontColor = Color;\n"
	"}\n"
	"\n"
	"";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader ColorVertShader(ColorVertText, ColorVert, ColorVertLength, ColorVertCheckSum);


#endif


#endif //_ColorVert_h_
