#ifndef _ColorFrag_h_
#define _ColorFrag_h_


// Header generated from binary by WriteAsBinHeader()..
static const int ColorFragLength = 34;
static const unsigned int ColorFrag[ColorFragLength]={
	0x20205350,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000002,	0x00000000,	0x00000000,	0x00000000,	0x00000001,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x0000000B,	0x00000000,	0x00000000,	0x00000000,
	0x00FA10E4,	0x00000000,	0x00000000,	0x00000000,	0x1E000000,	0x00000000,	0x00000000,	0x0000000A,	0x00000009,	0x00000000,
	0x00000000,	0x6E6F7246,	0x6C6F4374,	0x0000726F,};

//checksum generated by simpleCheckSum()
static const unsigned int ColorFragCheckSum = 71;

static const char* ColorFragText = 
	"\n"
	"#-------------------------------------------------\n"
	"# ORION - OpenGL ES 2.0 Shading Language Compiler\n"
	"# SAMSUNG INDIA SOFTWARE OPERATIONS PVT. LTD.\n"
	"# Compiler Version    : v04.00.03\n"
	"# Release Date        : 30.06.2008\n"
	"# FIMG VERSION      : FIMGv1.5\n"
	"# Optimizer Options :  -O\n"
	"#-------------------------------------------------\n"
	"\n"
	"ps_3_0\n"
	"\n"
	"fimg_version    0x01020000\n"
	"\n"
	"dcl_f4_FrontColor    v0.x\n"
	"\n"
	"label start\n"
	"label main_end\n"
	"mov_sat oColor.xyzw, v0.xyzw\n"
	"ret\n"
	"";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader ColorFragShader(ColorFragText, ColorFrag, ColorFragLength, ColorFragCheckSum);


#endif


#endif //_ColorFrag_h_
