#ifndef _FlatVert_h_
#define _FlatVert_h_


// Header generated from binary by WriteAsBinHeader()..
static const int FlatVertLength = 89;
static const unsigned int FlatVert[FlatVertLength]={
	0x20205356,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000005,	0x00000006,	0x00000000,	0x00000000,	0x00000001,	0x00000001,
	0x00000001,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x0000002D,	0x00000000,	0x00000000,	0x02020000,
	0x237820E4,	0x00000000,	0x00E40100,	0x02035500,	0x2EF820E4,	0x00000000,	0x00E40100,	0x0204AA00,	0x2EF820E4,	0x00000000,
	0x00E40100,	0x0205FF00,	0x0EF800E4,	0x00000000,	0x00000000,	0x00000000,	0x1E000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x3F800000,	0x3F800000,	0x3F800000,	0x3F800000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x0000000C,	0x00000006,	0x00000009,	0x00000000,	0x00000000,	0x00000000,	0x0000000B,	0x00000009,
	0x00010004,	0x00000000,	0x00000013,	0x00000019,	0x0000000E,	0x00020001,	0x00000008,	0x505F6C67,	0x7469736F,	0x006E6F69,
	0x74726556,	0x4D007865,	0x6C65646F,	0x77656956,	0x6A6F7250,	0x69746365,	0x614D6E6F,	0x78697274,	0x00000000,};

//checksum generated by simpleCheckSum()
static const unsigned int FlatVertCheckSum = 53;

static const char* FlatVertText = 
	"#ifdef GL_ES\n"
	"precision highp float;\n"
	"#endif\n"
	"\n"
	"attribute vec4 Vertex;\n"
	"\n"
	"uniform mat4 ModelViewProjectionMatrix;\n"
	"\n"
	"void main()\n"
	"{\n"
	"    gl_Position = ModelViewProjectionMatrix * Vertex;\n"
	"}\n"
	"\n"
	"";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader FlatVertShader(FlatVertText, FlatVert, FlatVertLength, FlatVertCheckSum);


#endif


#endif //_FlatVert_h_
