#ifndef _FogFrag_h_
#define _FogFrag_h_


// Header generated from binary by WriteAsBinHeader()..
static const int FogFragLength = 257;
static const unsigned int FogFrag[FogFragLength]={
	0x20205350,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000018,	0x0000000F,	0x00000000,	0x00000000,	0x00000003,	0x00000000,
	0x00000007,	0x00000001,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000070,	0x00000000,	0x00000000,	0x0000E407,
	0x107822E4,	0x00000000,	0x01000000,	0x0102E400,	0x037821E4,	0x00000000,	0x03000000,	0x02090002,	0x0C086100,	0x00000000,
	0x00000000,	0x06010000,	0x18800300,	0x00000000,	0x06000000,	0x40020002,	0x02102000,	0x00000000,	0x08000000,	0x01000002,
	0x030A2055,	0x00000000,	0x00000000,	0x00000000,	0x18000D00,	0x00000000,	0x0C000000,	0x02090002,	0x0C086100,	0x00000000,
	0x00000000,	0x06010000,	0x18800400,	0x00000000,	0x02000000,	0x42040000,	0x03102000,	0x00000000,	0x0D000000,	0x01000002,
	0x03102055,	0x00000000,	0x00000000,	0x01000000,	0x060A2055,	0x00000000,	0x00000000,	0x00000000,	0x18000700,	0x00000000,
	0x0E000000,	0x02090002,	0x0C086100,	0x00000000,	0x00000000,	0x06010000,	0x18800500,	0x00000000,	0x04000000,	0x42040002,
	0x03102000,	0x00000000,	0x02000000,	0x01000000,	0x03102055,	0x00000000,	0x02000000,	0x01000000,	0x03102055,	0x00000000,
	0x0D000000,	0x01000002,	0x03102055,	0x00000000,	0x00000000,	0x01000000,	0x060A2055,	0x00000000,	0x01000000,	0x4100E402,
	0x02782200,	0x00000000,	0x07000000,	0x0102E402,	0x237822E4,	0x00000000,	0x00E40102,	0x01010001,	0x0EFA10E4,	0x00000000,
	0x00000000,	0x00000000,	0x1E000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x3F800000,	0x3F800000,
	0x3F800000,	0x3F800000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x3F800000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x3F800000,	0x00000000,
	0x00000000,	0x00000000,	0x40000000,	0x00000000,	0x00000000,	0x00000000,	0x3FB8AA3B,	0x00000000,	0x00000000,	0x00000000,
	0x40400000,	0x00000000,	0x00000000,	0x00000000,	0x00000013,	0x00000009,	0x00000009,	0x00000000,	0x00000000,	0x0000001D,
	0x0000000A,	0x00000009,	0x00000000,	0x00000004,	0x00000028,	0x0000000C,	0x00000000,	0x00000000,	0x00000008,	0x00000000,
	0x00000007,	0x00000003,	0x00020001,	0x00000008,	0x00000035,	0x0000000B,	0x00000000,	0x00020001,	0x00000010,	0x00000041,
	0x00000009,	0x00000000,	0x00020001,	0x00000014,	0x0000004B,	0x00000007,	0x00000000,	0x00020001,	0x00000018,	0x00000053,
	0x00000009,	0x00000009,	0x00020001,	0x0000001C,	0x0000005D,	0x00000009,	0x00000000,	0x00020001,	0x00000020,	0x00000067,
	0x00000008,	0x00000001,	0x00020001,	0x00000024,	0x00000008,	0x0000000A,	0x0000000F,	0x00030005,	0x00000000,	0x44786554,
	0x00306D69,	0x49786554,	0x6567616D,	0x54003073,	0x6F437865,	0x3064726F,	0x6F724600,	0x6F43746E,	0x00726F6C,	0x46676F46,
	0x43676172,	0x64726F6F,	0x676F4600,	0x6E65642E,	0x79746973,	0x676F4600,	0x6174732E,	0x46007472,	0x652E676F,	0x4600646E,
	0x632E676F,	0x726F6C6F,	0x676F4600,	0x6163732E,	0x4600656C,	0x6D2E676F,	0x0065646F,};

//checksum generated by simpleCheckSum()
static const unsigned int FogFragCheckSum = 143;

static const char* FogFragText = 
	"\n"
	"#-------------------------------------------------\n"
	"# ORION - OpenGL ES 2.0 Shading Language Compiler\n"
	"# SAMSUNG INDIA SOFTWARE OPERATIONS PVT. LTD.\n"
	"# Compiler Version    : v04.00.03\n"
	"# Release Date        : 30.06.2008\n"
	"# FIMG VERSION      : FIMGv1.5\n"
	"# Optimizer Options :  -O\n"
	"#-------------------------------------------------\n"
	"\n"
	"ps_3_0\n"
	"\n"
	"fimg_version    0x01020000\n"
	"\n"
	"dcl_f2_TexDim0    c2.x\n"
	"dcl_s2_TexImages0    s0\n"
	"dcl_f4_TexCoord0    v0.x\n"
	"dcl_f4_FrontColor    v1.x\n"
	"dcl_f1_FogFragCoord    v2.x\n"
	"dcl_f1_Fog.density    c4.x\n"
	"dcl_f1_Fog.start    c5.x\n"
	"dcl_f1_Fog.end    c6.x\n"
	"dcl_f4_Fog.color    c7.x\n"
	"dcl_f1_Fog.scale    c8.x\n"
	"dcl_i1_Fog.mode    c9.x\n"
	"\n"
	"def c13, 1.442695, 0, 0, 0\n"
	"def c11, 1.000000, 0, 0, 0\n"
	"def c3, 1, 0, 0, 0\n"
	"def c1, 1.0, 1.0, 1.0, 1.0\n"
	"def c0, 0.0, 0.0, 0.0, 0.0\n"
	"def c10, 0.000000, 0, 0, 0\n"
	"def c12, 2, 0, 0, 0\n"
	"def c14, 3, 0, 0, 0\n"
	"\n"
	"label start\n"
	"label main_\n"
	"texld r2.xyzw, v0.xyzw, s0    # TexImages0=s0\n"
	"mul r1.xyzw, r2.xyzw, v1.xyzw    # fragColor=r1.xyzw, FrontColor=v1.xyzw\n"
	"setp_eq p1.x, c9.x, c3.x\n"
	"bf L1, p1.x\n"
	"# mad_sat r0.x, c8.x, !v2.x, c6.x\n"
	"add r0.y, !v2.x, c6.x\n"
	"mul_sat r0.x, r0.y, c8.x    # fog=r0.x, FogFragCoord=!v2.x\n"
	"b L2\n"
	"label L1\n"
	"setp_eq p1.x, c9.x, c12.x\n"
	"bf L3, p1.x\n"
	"mul r0.y, !c4.x, v2.x    # FogFragCoord=v2.x\n"
	"mul r0.y, r0.y, c13.x\n"
	"exp_sat r0.x, r0.y\n"
	"b L2\n"
	"label L3\n"
	"setp_eq p1.x, c9.x, c14.x\n"
	"bf L2, p1.x\n"
	"mul r0.y, !c4.x, c4.x\n"
	"mul r0.y, r0.y, v2.x    # FogFragCoord=v2.x\n"
	"mul r0.y, r0.y, v2.x    # FogFragCoord=v2.x\n"
	"mul r0.y, r0.y, c13.x\n"
	"exp_sat r0.x, r0.y\n"
	"label L2\n"
	"add r2.xyzw, !r0.xxxx, c1.xyzw\n"
	"mul r2.xyzw, r2.xyzw, c7.xyzw    # fog=!r0.xxxx\n"
	"mad_sat oColor.xyzw, r1.xyzw, r0.xxxx, r2.xyzw    # fragColor=r1.xyzw, fog=r0.xxxx\n"
	"label main_end\n"
	"ret\n"
	"# 40 instructions, 16 C regs, 3 R regs \n"
	"";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader FogFragShader(FogFragText, FogFrag, FogFragLength, FogFragCheckSum);


#endif


#endif //_FogFrag_h_
