#ifndef _FogExp2Frag_h_
#define _FogExp2Frag_h_


// Header generated from binary by WriteAsBinHeader()..
static const int FogExp2FragLength = 189;
static const unsigned int FogExp2Frag[FogExp2FragLength]={
	0x20205350,	0xFFFF0008,	0x00000048,	0x01020000,	0x0000000A,	0x0000000C,	0x00000000,	0x00000000,	0x00000003,	0x00000000,
	0x00000007,	0x00000001,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000070,	0x00000000,	0x00000000,	0x0000E407,
	0x107821E4,	0x00000000,	0x01000000,	0x0101E400,	0x037821E4,	0x00000000,	0x03000000,	0x42030002,	0x03082000,	0x00000000,
	0x02000000,	0x01000000,	0x03082000,	0x00000000,	0x02000000,	0x01000000,	0x03082000,	0x00000000,	0x09000000,	0x01000002,
	0x03082000,	0x00000000,	0x00000000,	0x01000000,	0x260A2000,	0x00000000,	0x06E40206,	0x4100E402,	0x2EF82200,	0x00000000,
	0x00E40102,	0x01010001,	0x0EFA10E4,	0x00000000,	0x00000000,	0x00000000,	0x1E000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x3F800000,	0x3F800000,	0x3F800000,	0x3F800000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x3FB8AA3B,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x3F800000,	0x00000000,	0x00000000,	0x00000000,	0x00000013,	0x00000009,	0x00000009,	0x00000000,
	0x00000000,	0x0000001D,	0x0000000A,	0x00000009,	0x00000000,	0x00000004,	0x00000028,	0x0000000C,	0x00000000,	0x00000000,
	0x00000008,	0x00000000,	0x00000007,	0x00000003,	0x00020001,	0x00000008,	0x00000035,	0x0000000B,	0x00000000,	0x00020001,
	0x0000000C,	0x00000041,	0x00000009,	0x00000000,	0x00020001,	0x00000010,	0x0000004B,	0x00000007,	0x00000000,	0x00020001,
	0x00000014,	0x00000053,	0x00000009,	0x00000009,	0x00020001,	0x00000018,	0x0000005D,	0x00000009,	0x00000000,	0x00020001,
	0x0000001C,	0x00000067,	0x00000008,	0x00000001,	0x00020001,	0x00000020,	0x00000008,	0x0000000A,	0x0000000F,	0x00030005,
	0x00000000,	0x44786554,	0x00306D69,	0x49786554,	0x6567616D,	0x54003073,	0x6F437865,	0x3064726F,	0x6F724600,	0x6F43746E,
	0x00726F6C,	0x46676F46,	0x43676172,	0x64726F6F,	0x676F4600,	0x6E65642E,	0x79746973,	0x676F4600,	0x6174732E,	0x46007472,
	0x652E676F,	0x4600646E,	0x632E676F,	0x726F6C6F,	0x676F4600,	0x6163732E,	0x4600656C,	0x6D2E676F,	0x0065646F,};

//checksum generated by simpleCheckSum()
static const unsigned int FogExp2FragCheckSum = 199;

static const char* FogExp2FragText = 
	"\n"
	"#-------------------------------------------------\n"
	"# ORION - OpenGL ES 2.0 Shading Language Compiler\n"
	"# SAMSUNG INDIA SOFTWARE OPERATIONS PVT. LTD.\n"
	"# Compiler Version    : v04.00.03\n"
	"# Release Date        : 30.06.2008\n"
	"# FIMG VERSION      : FIMGv1.5\n"
	"# Optimizer Options :  -O\n"
	"#-------------------------------------------------\n"
	"\n"
	"ps_3_0\n"
	"\n"
	"fimg_version    0x01020000\n"
	"\n"
	"dcl_f2_TexDim0    c2.x\n"
	"dcl_s2_TexImages0    s0\n"
	"dcl_f4_TexCoord0    v0.x\n"
	"dcl_f4_FrontColor    v1.x\n"
	"dcl_f1_FogFragCoord    v2.x\n"
	"dcl_f1_Fog.density    c3.x\n"
	"dcl_f1_Fog.start    c4.x\n"
	"dcl_f1_Fog.end    c5.x\n"
	"dcl_f4_Fog.color    c6.x\n"
	"dcl_f1_Fog.scale    c7.x\n"
	"dcl_i1_Fog.mode    c8.x\n"
	"\n"
	"def c11, 1.000000, 0, 0, 0\n"
	"def c9, 1.442695, 0, 0, 0\n"
	"def c1, 1.0, 1.0, 1.0, 1.0\n"
	"def c0, 0.0, 0.0, 0.0, 0.0\n"
	"def c10, 0.000000, 0, 0, 0\n"
	"\n"
	"label start\n"
	"label main_\n"
	"texld r1.xyzw, v0.xyzw, s0    # TexImages0=s0\n"
	"mul r1.xyzw, r1.xyzw, v1.xyzw    # fragColor=r1.xyzw, FrontColor=v1.xyzw\n"
	"mul r0.x, !c3.x, c3.x\n"
	"mul r0.x, r0.x, v2.x    # FogFragCoord=v2.x\n"
	"mul r0.x, r0.x, v2.x    # FogFragCoord=v2.x\n"
	"mul r0.x, r0.x, c9.x\n"
	"exp_sat r0.x, r0.x\n"
	"# add r2.xyzw, c1.xyzw, !r0.xxxx    # fog=!r0.xxxx\n"
	"# mul r2.xyzw, r2.xyzw, c6.xyzw\n"
	"mad r2.xyzw, -r0.xxxx, c6.xyzw, c6.xyzw\n"
	"mad_sat oColor.xyzw, r1.xyzw, r0.xxxx, r2.xyzw    # fragColor=r1.xyzw, fog=r0.xxxx\n"
	"label main_end\n"
	"ret\n"
	"# 19 instructions, 13 C regs, 3 R regs \n"
	"";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader FogExp2FragShader(FogExp2FragText, FogExp2Frag, FogExp2FragLength, FogExp2FragCheckSum);


#endif


#endif //_FogExp2Frag_h_
