#ifndef _TexColCFrag_h_
#define _TexColCFrag_h_


// Header generated from binary by WriteAsBinHeader()..
static const int TexColCFragLength = 88;
static const unsigned int TexColCFrag[TexColCFragLength]={
	0x20205350,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000004,	0x00000004,	0x00000000,	0x00000000,	0x00000002,	0x00000000,
	0x00000002,	0x00000001,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000031,	0x00000000,	0x00000000,	0x0000E407,
	0x107821E4,	0x00000000,	0x01000000,	0x0101E400,	0x037821E4,	0x00000000,	0x03000000,	0x0101E402,	0x037A10E4,	0x00000000,
	0x00000000,	0x00000000,	0x1E000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x3F800000,	0x3F800000,
	0x3F800000,	0x3F800000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x0000001C,	0x00000009,	0x00000009,	0x00000000,	0x00000000,	0x00000026,	0x0000000A,	0x00000009,	0x00000000,	0x00000004,
	0x00000000,	0x00000007,	0x00000003,	0x00020001,	0x00000008,	0x00000013,	0x00000008,	0x00000009,	0x00020001,	0x0000000C,
	0x00000008,	0x0000000A,	0x0000000F,	0x00030005,	0x00000000,	0x44786554,	0x00306D69,	0x49786554,	0x6567616D,	0x54003073,
	0x6F437865,	0x00726F6C,	0x43786554,	0x64726F6F,	0x72460030,	0x43746E6F,	0x726F6C6F,	0x00000000,};

//checksum generated by simpleCheckSum()
static const unsigned int TexColCFragCheckSum = 103;

static const char* TexColCFragText = 
	"\n"
	"#-------------------------------------------------\n"
	"# ORION - OpenGL ES 2.0 Shading Language Compiler\n"
	"# SAMSUNG INDIA SOFTWARE OPERATIONS PVT. LTD.\n"
	"# Compiler Version    : v04.00.03\n"
	"# Release Date        : 30.06.2008\n"
	"# FIMG VERSION      : FIMGv1.5\n"
	"# Optimizer Options :  -O\n"
	"#-------------------------------------------------\n"
	"\n"
	"ps_3_0\n"
	"\n"
	"fimg_version    0x01020000\n"
	"\n"
	"dcl_f2_TexDim0    c2.x\n"
	"dcl_s2_TexImages0    s0\n"
	"dcl_f4_TexColor    c3.x\n"
	"dcl_f4_TexCoord0    v0.x\n"
	"dcl_f4_FrontColor    v1.x\n"
	"\n"
	"def c1, 1.0, 1.0, 1.0, 1.0\n"
	"def c0, 0.0, 0.0, 0.0, 0.0\n"
	"\n"
	"label start\n"
	"label main_\n"
	"texld r1.xyzw, v0.xyzw, s0    # TexImages0=s0\n"
	"mul r1.xyzw, r1.xyzw, v1.xyzw    # FrontColor=v1.xyzw\n"
	"mul_sat oColor.xyzw, r1.xyzw, c3.xyzw    # gl_FragColor=oColor.xyzw, TexColor=c3.xyzw\n"
	"label main_end\n"
	"ret\n"
	"# 11 instructions, 5 C regs, 2 R regs \n"
	"";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader TexColCFragShader(TexColCFragText, TexColCFrag, TexColCFragLength, TexColCFragCheckSum);


#endif


#endif //_TexColCFrag_h_
