#ifndef _TexColVert_h_
#define _TexColVert_h_


// Header generated from binary by WriteAsBinHeader()..
static const int TexColVertLength = 139;
static const unsigned int TexColVert[TexColVertLength]={
	0x20205356,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000007,	0x00000007,	0x00000000,	0x00000000,	0x00000003,	0x00000003,
	0x00000002,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000061,	0x00000000,	0x00000000,	0x02020000,
	0x237820E4,	0x00000000,	0x00E40100,	0x02035500,	0x2EF820E4,	0x00000000,	0x00E40100,	0x0204AA00,	0x2EF820E4,	0x00000000,
	0x00E40100,	0x0205FF00,	0x0EF800E4,	0x00000000,	0x06000000,	0x0002E402,	0x027802E4,	0x00000000,	0x00000000,	0x00010000,
	0x00F801E4,	0x00000000,	0x00000000,	0x00000000,	0x1E000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x3F800000,	0x3F800000,	0x3F800000,	0x3F800000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x0000000C,	0x00000006,	0x00000009,	0x00000000,	0x00000000,	0x00000013,
	0x00000005,	0x00000009,	0x00000000,	0x00000004,	0x00000019,	0x0000000E,	0x00000009,	0x00000000,	0x00000008,	0x00000000,
	0x0000000B,	0x00000009,	0x00010004,	0x00000000,	0x0000004C,	0x0000000A,	0x00000009,	0x00010004,	0x00000004,	0x00000057,
	0x00000009,	0x00000009,	0x00010004,	0x00000008,	0x00000028,	0x00000019,	0x0000000E,	0x00020001,	0x00000008,	0x00000042,
	0x00000009,	0x00000009,	0x00020001,	0x00000018,	0x505F6C67,	0x7469736F,	0x006E6F69,	0x74726556,	0x43007865,	0x726F6C6F,
	0x6C754D00,	0x65546974,	0x6F6F4378,	0x00306472,	0x65646F4D,	0x6569566C,	0x6F725077,	0x7463656A,	0x4D6E6F69,	0x69727461,
	0x65540078,	0x69685378,	0x00307466,	0x6E6F7246,	0x6C6F4374,	0x5400726F,	0x6F437865,	0x3064726F,	0x00000000,};

//checksum generated by simpleCheckSum()
static const unsigned int TexColVertCheckSum = 81;

static const char* TexColVertText = 
	"#ifdef GL_ES\n"
	"precision highp float;\n"
	"#endif\n"
	"\n"
	"attribute vec4 Vertex;\n"
	"attribute vec4 Color;\n"
	"attribute vec4 MultiTexCoord0;\n"
	"\n"
	"uniform mat4 ModelViewProjectionMatrix;\n"
	"uniform vec4 TexShift0;\n"
	"\n"
	"varying vec4 FrontColor;\n"
	"varying vec4 TexCoord0;\n"
	"\n"
	"void main()\n"
	"{\n"
	"    gl_Position = ModelViewProjectionMatrix * Vertex;\n"
	"    FrontColor = Color;\n"
	"    TexCoord0 = MultiTexCoord0 + TexShift0;\n"
	"}\n"
	"\n"
	"";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader TexColVertShader(TexColVertText, TexColVert, TexColVertLength, TexColVertCheckSum);


#endif


#endif //_TexColVert_h_
