#ifndef _TextureCFrag_h_
#define _TextureCFrag_h_


// Header generated from binary by WriteAsBinHeader()..
static const int TextureCFragLength = 76;
static const unsigned int TextureCFrag[TextureCFragLength]={
	0x20205350,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000003,	0x00000004,	0x00000000,	0x00000000,	0x00000001,	0x00000000,
	0x00000002,	0x00000001,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000028,	0x00000000,	0x00000000,	0x0000E407,
	0x107821E4,	0x00000000,	0x03000000,	0x0101E402,	0x037A10E4,	0x00000000,	0x00000000,	0x00000000,	0x1E000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x3F800000,	0x3F800000,	0x3F800000,	0x3F800000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000013,	0x00000009,	0x00000009,	0x00000000,
	0x00000000,	0x00000000,	0x00000007,	0x00000003,	0x00020001,	0x00000008,	0x0000001D,	0x0000000A,	0x00000009,	0x00020001,
	0x0000000C,	0x00000008,	0x0000000A,	0x0000000F,	0x00030005,	0x00000000,	0x44786554,	0x00306D69,	0x49786554,	0x6567616D,
	0x54003073,	0x6F437865,	0x3064726F,	0x6F724600,	0x6F43746E,	0x00726F6C,};

//checksum generated by simpleCheckSum()
static const unsigned int TextureCFragCheckSum = 23;

static const char* TextureCFragText = 
	"\n"
	"#-------------------------------------------------\n"
	"# ORION - OpenGL ES 2.0 Shading Language Compiler\n"
	"# SAMSUNG INDIA SOFTWARE OPERATIONS PVT. LTD.\n"
	"# Compiler Version    : v04.00.03\n"
	"# Release Date        : 30.06.2008\n"
	"# FIMG VERSION      : FIMGv1.5\n"
	"# Optimizer Options :  -O\n"
	"#-------------------------------------------------\n"
	"\n"
	"ps_3_0\n"
	"\n"
	"fimg_version    0x01020000\n"
	"\n"
	"dcl_f2_TexDim0    c2.x\n"
	"dcl_s2_TexImages0    s0\n"
	"dcl_f4_TexCoord0    v0.x\n"
	"dcl_f4_FrontColor    c3.x\n"
	"\n"
	"def c1, 1.0, 1.0, 1.0, 1.0\n"
	"def c0, 0.0, 0.0, 0.0, 0.0\n"
	"\n"
	"label start\n"
	"label main_\n"
	"texld r1.xyzw, v0.xyzw, s0    # TexImages0=s0\n"
	"mul_sat oColor.xyzw, r1.xyzw, c3.xyzw    # gl_FragColor=oColor.xyzw, FrontColor=c3.xyzw\n"
	"label main_end\n"
	"ret\n"
	"# 10 instructions, 5 C regs, 2 R regs \n"
	"";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader TextureCFragShader(TextureCFragText, TextureCFrag, TextureCFragLength, TextureCFragCheckSum);


#endif


#endif //_TextureCFrag_h_
