#ifndef _TextureVert_h_
#define _TextureVert_h_


// Header generated from binary by WriteAsBinHeader()..
static const int TextureVertLength = 120;
static const unsigned int TextureVert[TextureVertLength]={
	0x20205356,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000006,	0x00000007,	0x00000000,	0x00000000,	0x00000002,	0x00000002,
	0x00000002,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000050,	0x00000000,	0x00000000,	0x02020000,
	0x237820E4,	0x00000000,	0x00E40100,	0x02035500,	0x2EF820E4,	0x00000000,	0x00E40100,	0x0204AA00,	0x2EF820E4,	0x00000000,
	0x00E40100,	0x0205FF00,	0x0EF800E4,	0x00000000,	0x06000000,	0x0001E402,	0x027801E4,	0x00000000,	0x00000000,	0x00000000,
	0x1E000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x3F800000,	0x3F800000,	0x3F800000,	0x3F800000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x0000000C,	0x00000006,	0x00000009,	0x00000000,	0x00000000,	0x00000013,	0x0000000E,	0x00000009,	0x00000000,	0x00000004,
	0x00000000,	0x0000000B,	0x00000009,	0x00010004,	0x00000000,	0x00000046,	0x00000009,	0x00000009,	0x00010004,	0x00000004,
	0x00000022,	0x00000019,	0x0000000E,	0x00020001,	0x00000008,	0x0000003C,	0x00000009,	0x00000009,	0x00020001,	0x00000018,
	0x505F6C67,	0x7469736F,	0x006E6F69,	0x74726556,	0x4D007865,	0x69746C75,	0x43786554,	0x64726F6F,	0x6F4D0030,	0x566C6564,
	0x50776569,	0x656A6F72,	0x6F697463,	0x74614D6E,	0x00786972,	0x53786554,	0x74666968,	0x65540030,	0x6F6F4378,	0x00306472,};

//checksum generated by simpleCheckSum()
static const unsigned int TextureVertCheckSum = 6;

static const char* TextureVertText = 
	"#ifdef GL_ES\n"
	"precision highp float;\n"
	"#endif\n"
	"\n"
	"attribute vec4 Vertex;\n"
	"attribute vec4 MultiTexCoord0;\n"
	"\n"
	"uniform mat4 ModelViewProjectionMatrix;\n"
	"uniform vec4 TexShift0;\n"
	"\n"
	"varying vec4 TexCoord0;\n"
	"invariant gl_Position;\n"
	"\n"
	"void main()\n"
	"{\n"
	"    gl_Position = ModelViewProjectionMatrix * Vertex;\n"
	"    TexCoord0 = MultiTexCoord0 + TexShift0;\n"
	"}\n"
	"\n"
	"";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader TextureVertShader(TextureVertText, TextureVert, TextureVertLength, TextureVertCheckSum);


#endif


#endif //_TextureVert_h_
